version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins-ansible
    build:
      context: E:\Github\Repositorios\Courses\Jenkins\jenkins_ansible
    ports:
      - "8085:8080"
    volumes:
      - //E/docker/jenkins_home:/var/jenkins_home
    networks: 
      - net
  remote_host:
    container_name: remote-host
    image: remote-host
    build:
      context: E:\Github\Repositorios\Courses\Jenkins\centos7
    volumes:
      - //E/docker/remote_host/script.sh:/tmp/script.sh
    networks:
      - net
  db_host:
    container_name: db_host
    image: mysql:5.7
    environment: 
      - MYSQL_ROOT_PASSWORD= "1234"
    volumes:
      - //E/docker/db_host:/var/lib/mysql
    networks:
      - net
  web: 
    container_name: web
    image: ansible-web
    build:
      context: E:\Github\Repositorios\Courses\Jenkins\jenkins_ansible\web
    ports:
      - "88:88"
    networks:
      - net
  git:
    container_name: git-server
    hostname: gitlab.example.com
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - //E/docker/git_server/config:/etc/gitlab
      - //E/docker/git_server/logs:/var/log/gitlab
      - //E/docker/git_server/data:/var/opt
    image: gitlab/gitlab-ce
    networks:
      - net
networks: 
  net: