version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    volumes:
      - //E/Github/Repositorios/Courses/Jenkins/jenkins_home:/var/jenkins_home
    networks: 
      - net
  remote_host:
    container_name: remote-host
    image: remote-host
    build:
      context: E:\Github\Repositorios\Courses\Jenkins\centos7
    networks:
      - net
networks: 
  net: